name: Test BlockImageUpdate

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download IMG Patch Tools
        run: |
          wget -q \
            https://github.com/erfanoabdi/imgpatchtools/releases/download/0.3/IMG_Patch_Tools_0.3.zip \
            -O imgpatchtools.zip

          unzip -q imgpatchtools.zip

          chmod +x IMG_Patch_Tools_0.3/Linux_x64/*

      - name: Show Help
        run: |
          echo "===== BlockImageUpdate ====="
          ./IMG_Patch_Tools_0.3/Linux_x64/BlockImageUpdate || true

          echo ""

          echo "===== BlockImageVerify ====="
          ./IMG_Patch_Tools_0.3/Linux_x64/BlockImageVerify || true

          echo ""

          echo "===== ApplyPatch ====="
          ./IMG_Patch_Tools_0.3/Linux_x64/ApplyPatch || true
