name: test-odm-rebuild

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  odm:
    runs-on: ubuntu-latest

    steps:
      - name: Download OTA artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: adamwasowicz9-yansk/johnas
          run-id: 27723007988
          name: ota
          path: ota

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y unzip simg2img python3

      - name: Extract ODM files
        run: |
          mkdir work

          unzip -j ota/ota.zip \
            odm.transfer.list \
            odm.new.dat \
            odm.patch.dat \
            -d work

          ls -lah work

      - name: Inspect transfer list
        run: |
          echo "===== ODM TRANSFER ====="
          cat work/odm.transfer.list

      - name: Create blank image
        run: |
          BLOCKS=$(tail -n +5 work/odm.transfer.list | \
            tr ',' '\n' | \
            sort -n | \
            tail -1)

          echo "Max block: $BLOCKS"

          dd if=/dev/zero \
             of=work/odm.img \
             bs=4096 \
             count=$((BLOCKS+1024))

          ls -lh work/odm.img

      - name: Download imgpatchtools
        run: |
          git clone https://github.com/erfanoabdi/imgpatchtools.git
          cd imgpatchtools

          make || true

      - name: Try patch ODM
        run: |
          cd imgpatchtools

          ./BlockImageUpdate \
            ../work/odm.img \
            ../work/odm.transfer.list \
            ../work/odm.new.dat \
            ../work/odm.patch.dat || true

      - name: Check result
        run: |
          file work/odm.img || true
          ls -lh work/odm.img

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: odm-test
          path: work/*
